say:
  name: Say
  description: Use Gemini AI to convert text to speech
  fields:
    message:
      name: Message
      description: Text to convert to speech
      required: true
      example: "Hello, how are you today?"
    voice:
      name: Voice
      description: Voice to use for speech synthesis
      default: "Aoede"
      example: "Aoede"
    speed:
      name: Speed
      description: Speech speed (0.25 to 4.0)
      default: 1.0
      example: 1.0
    cache:
      name: Cache
      description: Whether to cache the generated audio
      default: true
      example: true
    language:
      name: Language
      description: Language code for the text
      default: "en"
      example: "en"

transcribe:
  name: Transcribe
  description: Use Gemini AI to convert speech to text
  fields:
    audio_file:
      name: Audio File
      description: Path to audio file to transcribe
      required: true
      example: "/config/audio/recording.wav"
    language:
      name: Language
      description: Language of the audio
      example: "en"
    model:
      name: Model
      description: Gemini model to use for transcription
      default: "gemini-2.0-flash"
      example: "gemini-2.0-flash"

process:
  name: Process
  description: Process conversation with Gemini AI
  fields:
    text:
      name: Text
      description: Text to process
      required: true
      example: "What's the weather today?"
    conversation_id:
      name: Conversation ID
      description: ID to maintain conversation context
      default: "default"
      example: "default"
    system_prompt:
      name: System Prompt
      description: Custom system prompt for this conversation
      example: "You are a helpful assistant"
    language:
      name: Language
      description: Language code for the conversation
      default: "en"
      example: "en"
    model:
      name: Model
      description: Gemini model to use for conversation
      default: "gemini-2.0-flash"
      example: "gemini-2.0-flash"

preview_voice:
  name: Preview Voice
  description: Preview a voice with sample text
  fields:
    voice:
      name: Voice
      description: Voice to preview
      required: true
      example: "Aoede"
    text:
      name: Sample Text
      description: Text to use for preview
      default: "Hello, this is a voice preview."
      example: "Hello, this is a voice preview."
    speed:
      name: Speed
      description: Speech speed for preview (0.25 to 4.0)
      default: 1.0
      example: 1.0